version: 2.1
jobs:
  # job to build image and push to docker hub
  # job to pull down image and deploy on server
  test:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.17
      - image: postgres:13.3
        environment:
          POSTGRES_USER: circleci
          POSTGRES_HOST_AUTH_METHOD: trust

    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v5-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v5-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run: go get -u github.com/pressly/goose/v3/cmd/goose
      - run:
          name: DB Setup
          command: ./scripts/refresh_database.sh
          environment:
            DB_USERNAME: circleci
            DB_HOST: localhost
      - run:
          name: Run tests
          command: go test -p 1 ./... -v
          environment:
            DB_USERNAME: circleci
            DB_HOST: localhost

workflows:
  testing:
    jobs:
      - test
