name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Set Up ENV
      run: export DB_USERNAME=postgres

    - name: Install Database
      run: apt-get update && apt-get -y install postgresql
      
    - name: Setup Database
      run: ./script/refresh_database.sh

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
