name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    container-job:
      runs-on: ubuntu-latest
      container: golang:alpine
      services:
        postgres:
          image: postgres
          env: 
            POSTGRES_PASSWORD: ''

      steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      # - name: Set Up ENV
      #   run: export DB_USERNAME=postgres

      # - name: Install Database
      #   run: psql --version #sudo apt-get update && sudo apt-get -y install postgresql

      - name: Setup Database
        run: ./scripts/refresh_database.sh
        env:
          DB_USERNAME: postgres

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
